name: McLetterNumberBlocks
version: '${project.version}'
main: me.stephanosbad.edublocks.mcletternumberblocks.McLetterNumberBlocks
api-version: 1.18
authors: [ stephanosbad ]
description: Letter and number blocks for use by education plugins
depend: [ Oraxen ]
softdepend: [ WorldGuard, GriefPrevention ]
commands:
  charblock:
    usage: /charblock <player> <string>
    description: Give a string of letter or number blocks to a player.