name: McLetterNumberBlocks
version: '${project.version}'
main: me.stephanosbad.edublocks.mcletternumberblocks.McLetterNumberBlocks
api-version: 1.18
authors: [ stephanosbad ]
description: Letter and number blocks for use by education plugins
depend: [WorldGuard]
commands:
  charblock:
    usage: /charblock <player> <item> <amount>
    description: Give a letter or number block to a player.