name: McLetterNumberBlocks
version: '${project.version}'
main: me.stephanosbad.edublocks.mcletternumberblocks.McLetterNumberBlocks
api-version: 1.18
authors: [ stephanosbad ]
description: Letter and number blocks for use by education plugins
